---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name: 
        - php5
        - apache2 
        - libapache2-mod-php5
        - php5-gd
        - mysql-server-5.6
        - libssh2-php
        - php5-mcrypt
        - python-mysqldb
        - php5-mysql
        state: latest
      become: yes
    - name: 'Cria o Banco do Mysql'
      mysql_db:
          name: wordpress_db
          loguin_user: 'root'
          #loguin_password:
          state: present
          